### ISSUE TITLE
[BUG]: IsTrailerAttachedToVehicle

### ISSUE THREAD

**Issue by Sancky** [openmultiplayer/server-beta-old#45] opened 2022-04-23 17:59 UTC
# Description

IsTrailerAttachedToVehicle returns true when trailer is not attached on vehicle.

# How to re-produce this bug

-

# Relevant log output

-

# open.mp server version

build 2

# Operating system or distribution

-

# Contact information

Sancky#3199

# Additional information

-

**Comment by ksenonadv** [comment] 2022-04-23 19:51
Hello, could you please offer us more context to this issue?
When exactly this function fails to return accurate data?

**Comment by Sancky** [comment] 2022-04-23 19:59
After i detach the trailer from the truck.

**Comment by ksenonadv** [comment] 2022-04-23 20:06
> After i detach the trailer from the truck.

Are u using DetachTrailerFromVehicle or are you detaching in game?

**Comment by Sancky** [comment] 2022-04-23 20:06
In game.

**Comment by ksenonadv** [comment] 2022-04-24 11:27
Did some changes to trailer sync. I can't reproduce this anymore on my end. I will close this issue for now. If the bug is still happening after next build release please open a new one.

**Closed as completed by ksenonadv** 2022-04-24 11:27 UTC
Labels: bug
