### ISSUE TITLE
[BUG]: NetStats_GetConnectedTime returning wrong value

### ISSUE THREAD

**Issue by RodrigoMSR** [openmultiplayer/server-beta-old#116] opened 2022-06-28 15:03 UTC
# Description

NetStats_GetConnectedTime is returning a random static value.

# How to re-produce this bug

See the value returned by NetStats_GetConnectedTime, it will be the same every time.

# open.mp server version

[open.mp server public beta build 5](https://github.com/openmultiplayer/server-beta/releases/tag/build5)

# Operating system or distribution

*Windows 10 and Debian 10*

**Comment by ksenonadv** [comment] 2022-06-28 15:11
Duplicate of #107

**Closed as completed by ksenonadv** 2022-06-28 15:11 UTC
Labels: bug, duplicate
