### ISSUE TITLE
[BUG] OnPlayerRquestClass

### ISSUE THREAD

**Issue by FeveranN** [openmultiplayer/server-beta-old#13] opened 2022-04-20 21:57 UTC
# Description

*Samp OnPlayerRquestClass is showing but Open:MP spawns before OnPlayerRquestClass*

# How to re-produce this behavior difference

*Tell us a how to re-produce this behavior:*

1. *Use gamemode grandlarc.amx*
2. *run the omp-server.exe*
3. *Do it spawn*

# Relevant log output

```
Samp return OnplayerRequestClass callback
https://www.hizliresim.com/no65cx2*

Open:Mp dont exits OnplayerRequestClass callback
https://www.hizliresim.com/db0w3u1
```

# open.mp server version

*[open.mp server public beta build 1](https://github.com/openmultiplayer/server-beta/releases/tag/build1)*

# Operating system or distribution

*Windows 10 64 Bit*

# Contact information

*Feveran#8848*

# Additional information

*None*

**Comment by AmyrAhmady** [comment] 2022-04-21 01:27
Thanks for your report, it's a duplicate of #3 if you think I've made a mistake about it, just tell us to reopen the issue or make a new one

**Closed as completed by AmyrAhmady** 2022-04-21 01:27 UTC
Labels: duplicate
